### ISSUE TITLE
tex does not render correctly

### ISSUE THREAD

**Issue by felbinger** [felbinger/AdminGuide#25]
![image](https://user-images.githubusercontent.com/26925347/106563354-f0a0c800-652b-11eb-8ed8-8f03f379d3c2.png)
https://github.com/felbinger/AdminGuide/blame/master/docs/installation/stack-logic.md#L31-L32

**Comment by MarcelCoding** [comment]
![image](https://user-images.githubusercontent.com/34819524/106576930-015a3980-653e-11eb-8fb0-64aabdc34639.png)
