### ISSUE TITLE
Matrix Service: Add bridges

### ISSUE THREAD

**Issue by felbinger** [felbinger/AdminGuide#26]
Add bridges to matrix:
* [Telegram](https://github.com/tulir/mautrix-telegram) :heavy_check_mark: 
* [Signal](https://github.com/tulir/mautrix-signal) :heavy_check_mark: 
* [WhatsApp](https://github.com/tulir/mautrix-whatsapp) :heavy_check_mark: 
* [Instagram](https://github.com/tulir/mautrix-instagram) :x: 
* [Discord](https://github.com/matrix-discord/mx-puppet-discord) or [Discord (alternative)](https://github.com/Half-Shot/matrix-appservice-discord) :x:

I already tested the telegram and signal bridge from `tulir`, the setup instructions are easy to follow.

**Comment by Tert0** [comment]
I'm currently working on the Guide for Signal
